(define (problem BLOCKS)
(:domain BLOCKS)
(:objects A E P S T H Y O G D C L R I B - block)
(:INIT   (ONTABLE A)
         (ON B A)
         (CLEAR O) (ON O B)
         (ON E P)
         (ON I E) (CLEAR I)
         (ONTABLE P)
         (ONTABLE S)
         (ON T S) 
         (CLEAR T)
         (ONTABLE Y)
         (ON L Y) (CLEAR L) 
         (ONTABLE G) 
         (ON R G)(CLEAR R)
         (ONTABLE C) 
         (CLEAR C)
         (ONTABLE D)
         (CLEAR H) (ON H D)
         (HANDEMPTY)
)
(:goal (AND 
        (ONTABLE B)
        (ON A B)
        (ON T A)
        (ON S T)
        )
    )
)
