(define (problem BLOCKS)
(:domain BLOCKS)
(:objects A E P S T H Y O G D C R I - block)
(:INIT   (ONTABLE A)
         (CLEAR O) (ON O A)
         (ON E P)
         (ON I E) (CLEAR I)
         (ONTABLE P)
         (ONTABLE S)
         (ON T S) 
         (CLEAR T)
         (ONTABLE Y)
         (CLEAR Y) 
         (ONTABLE G) 
         (ON R G)(CLEAR R)
         (ONTABLE C) 
         (CLEAR C)
         (ONTABLE D)
         (CLEAR H) (ON H D)
         (HANDEMPTY)
)
(:goal (AND 
        (ONTABLE G)
        (ON O G)
        (ON D O)
        )
    )
)
