(define (problem logistics)
  (:domain logistics)
(:goal 
	(or 
	    (and (in pkg1 truck1) (in pkg3 truck1) (in pkg5 truck1))
		(and (in pkg2 truck1) (in pkg3 truck1) (in pkg5 truck1))
	    (and (in pkg1 truck1) (in pkg4 truck1) (in pkg5 truck1))
	    (and (in pkg2 truck1) (in pkg4 truck1) (in pkg5 truck1))
        (and (in pkg1 truck1) (in pkg3 truck1) (in pkg6 truck1))
		(and (in pkg2 truck1) (in pkg3 truck1) (in pkg6 truck1))
	    (and (in pkg1 truck1) (in pkg4 truck1) (in pkg6 truck1))
	    (and (in pkg2 truck1) (in pkg4 truck1) (in pkg6 truck1))
	    (and (in pkg1 truck2) (in pkg3 truck2) (in pkg5 truck2))
		(and (in pkg2 truck2) (in pkg3 truck2) (in pkg5 truck2))
	    (and (in pkg1 truck2) (in pkg4 truck2) (in pkg5 truck2))
	    (and (in pkg2 truck2) (in pkg4 truck2) (in pkg5 truck2))
        (and (in pkg1 truck2) (in pkg3 truck2) (in pkg6 truck2))
		(and (in pkg2 truck2) (in pkg3 truck2) (in pkg6 truck2))
	    (and (in pkg1 truck2) (in pkg4 truck2) (in pkg6 truck2))
	    (and (in pkg2 truck2) (in pkg4 truck2) (in pkg6 truck2))
	    (and (in pkg1 truck3) (in pkg3 truck3) (in pkg5 truck3))
		(and (in pkg2 truck3) (in pkg3 truck3) (in pkg5 truck3))
	    (and (in pkg1 truck3) (in pkg4 truck3) (in pkg5 truck3))
	    (and (in pkg2 truck3) (in pkg4 truck3) (in pkg5 truck3))
        (and (in pkg1 truck3) (in pkg3 truck3) (in pkg6 truck3))
		(and (in pkg2 truck3) (in pkg3 truck3) (in pkg6 truck3))
	    (and (in pkg1 truck3) (in pkg4 truck3) (in pkg6 truck3))
	    (and (in pkg2 truck3) (in pkg4 truck3) (in pkg6 truck3))
	    (and (in pkg1 truck4) (in pkg3 truck4) (in pkg5 truck4))
		(and (in pkg2 truck4) (in pkg3 truck4) (in pkg5 truck4))
	    (and (in pkg1 truck4) (in pkg4 truck4) (in pkg5 truck4))
	    (and (in pkg2 truck4) (in pkg4 truck4) (in pkg5 truck4))
        (and (in pkg1 truck4) (in pkg3 truck4) (in pkg6 truck4))
		(and (in pkg2 truck4) (in pkg3 truck4) (in pkg6 truck4))
	    (and (in pkg1 truck4) (in pkg4 truck4) (in pkg6 truck4))
	    (and (in pkg2 truck4) (in pkg4 truck4) (in pkg6 truck4))
	)
)
)
