(define (problem BLOCKS)
(:domain BLOCKS)
(:objects A E P S T H Y O G D C L Z R I - block)
(:INIT   (ONTABLE A)
         (CLEAR O) (ON O A)
         (ON E P)
         (ON I E) (CLEAR I)
         (ONTABLE P)
         (ONTABLE S)
         (ON T S) (CLEAR T)
         (ONTABLE Y)
         (ON L Y) (CLEAR L) 
         (ONTABLE G) 
         (ON R G)(CLEAR R)
         (ONTABLE C) 
         (ON Z C) (CLEAR Z)
         (ONTABLE D)
         (CLEAR H) (ON H D)
         (HANDEMPTY)
)
(:goal (AND 
        ; S C R I P T
        (ONTABLE T)
        (ON P T)
        (ON I P)
        (ON R I)
        (ON C R)
        (ON S C)
        )
    )
)
           
